### ISSUE TITLE
Error when running the example_feat_extract.py

### ISSUE THREAD

**Issue by berryweinst** [tomrunia/TF_FeatureExtraction#10]
Hi,
Maybe I'm missing something but after following the 3 steps + cloning the 'TF_FeatureExtraction' git itself. I run:
python example_feat_extract.py --network resnet_v1_50 --checkpoint ../resnet_v1_50.ckpt --image_path ../../studies/ECoG/video_data/frames/ --out_file ../features.h5 --num_classes 1000 --layer_names resnet_v1_50/logits

and getting this error:
Traceback (most recent call last):
  File "example_feat_extract.py", line 24, in <module>
    from feature_extractor.feature_extractor import FeatureExtractor
  File "/Users/berryweinstein/tensorflow/TF_FeatureExtraction/feature_extractor/feature_extractor.py", line 20, in <module>
    from nets import nets_factory
ModuleNotFoundError: No module named 'nets'

Can you please advise?

**Comment by Soldelli** [comment]
I have the same problem, have anyone found a solution?

**Comment by hamjam** [comment]
Are you sure about cloning tensorflow/models and setting $PYTHONPATH variable turely?

**Comment by HetSP07** [comment]
You should fix the path 
export PYTHONPATH="<checkout_dir>/research/slim:$PYTHONPATH"
