### ISSUE TITLE
The Error When I debug  the file of " example_feat_extract.py"

### ISSUE THREAD

**Issue by yingning** [tomrunia/TF_FeatureExtraction#4]
Hello , firstly, thanks for your shared code! 
The following are Error when I debug the file of "example_feat_extract.py"  :

File "/home/jsj/TF_FeatureExtraction/example_feat_extract.py", line 25, in <module>
    import feature_extractor.utils as utils
  File "/home/jsj/TF_FeatureExtraction/feature_extractor/utils.py", line 23, in <module>
    from datasets import imagenet
ImportError: No module named datasets

Do I need to creat a file of dataset and then download the imagenet data? Any suggestion will be appreciated!@tomrunia

**Comment by tomrunia** [comment]
Hi, no you just need to make sure it can find the datasets package included in the `tensorflow/datasets` repository. It seems like they recently changed the file structure of that repository, but you can find those files here: `https://github.com/tensorflow/models/tree/master/research/slim`. Just add that path to your `PYTHONPATH` and you should be fine :)

**Comment by yingning** [comment]
Thanks you for your response ! Your suggestion works well! @tomrunia

**Comment by diaoxue** [comment]
RuntimeError: module compiled against API version 0xa but this version of numpy is 0x9
RuntimeError: module compiled against API version 0xa but this version of numpy is 0x9
Traceback (most recent call last):
  File "./example_feat_extract.py", line 24, in <module>
    from feature_extractor.feature_extractor import FeatureExtractor
  File "/home/defy/TF_FeatureExtraction/feature_extractor/feature_extractor.py", line 19, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.4/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
SystemError: initialization of _pywrap_tensorflow_internal raised unreported exception

update numpy, but do not work, thanks
