### ISSUE TITLE
SystemError: initialization of _pywrap_tensorflow_internal raised unreported exception

### ISSUE THREAD

**Issue by diaoxue** [tomrunia/TF_FeatureExtraction#7]
RuntimeError: module compiled against API version 0xa but this version of numpy is 0x9
RuntimeError: module compiled against API version 0xa but this version of numpy is 0x9
Traceback (most recent call last):
  File "./example_feat_extract.py", line 24, in <module>
    from feature_extractor.feature_extractor import FeatureExtractor
  File "/home/defy/TF_FeatureExtraction/feature_extractor/feature_extractor.py", line 19, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.4/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
SystemError: initialization of _pywrap_tensorflow_internal raised unreported exception

update numpy, but do not work

thanks

**Comment by Lucky94** [comment]
Hi @diaoxue, 
I guess you are running the script from tensorflow root directory. Try running it from somewhere else (any other directory), it should work.

Hope it helps.
Regards,
Lucky Srivastava
